version: '3'
vars:
  PAGES:
    - https://fabtcg.com/en/resources/card-galleries/welcome-rathe-booster/
    # - https://fabtcg.com/en/resources/card-galleries/welcome-rathe-unlimited-booster/
    # - https://fabtcg.com/en/resources/card-galleries/arcane-rising/
    # - https://fabtcg.com/en/resources/card-galleries/arcane-rising-unlimited-booster/
    # - https://fabtcg.com/en/resources/card-galleries/crucible-war-booster/
    # - https://fabtcg.com/en/resources/card-galleries/crucible-war-unlimited/
    # - https://fabtcg.com/en/resources/card-galleries/monarch-booster/
    # - https://fabtcg.com/en/resources/card-galleries/monarch-booster-unlimited/
    # - https://fabtcg.com/en/resources/card-galleries/tales-aria-booster/
    # - https://fabtcg.com/en/resources/card-galleries/tales-aria-unlimited/
    # - https://fabtcg.com/en/resources/card-galleries/everfest-booster/
    # - https://fabtcg.com/en/resources/card-galleries/history-pack-1-en-booster/
    # - https://fabtcg.com/en/resources/card-galleries/uprising/
    # - https://fabtcg.com/en/resources/card-galleries/dynasty/
    # - https://fabtcg.com/en/resources/card-galleries/outsiders/
    # - https://fabtcg.com/en/resources/card-galleries/dusk-till-dawn/
    # - https://fabtcg.com/en/resources/card-galleries/round-the-table-tcc-x-lss/
    # - https://fabtcg.com/en/resources/card-galleries/bright-lights/
    # - https://fabtcg.com/en/resources/card-galleries/heavy-hitters/
    # - https://fabtcg.com/en/resources/card-galleries/part-the-mistveil-en/
  DOWNLOAD_DIR: $HOME/Downloads/fab
  DOWNLOAD_CONCURRENCY: 3
  DOCKER_VOLUME_NAME: fab-cards
tasks:
  build:
    cmds:
      - docker build . -f ./docker/Dockerfile.image-scraper -t fab/image-scraper:latest
  scrape:
    cmds:
      - mkdir -p {{$.DOWNLOAD_DIR}}
      - for: {var: PAGES}
        cmd: |
          docker run --rm \
          -e PAGE_URL={{$.ITEM}} \
          -e DOWNLOAD_DIR=/downloads \
          -e DOWNLOAD_CONCURRENCY={{$.DOWNLOAD_CONCURRENCY}} \
          -v {{$.DOCKER_VOLUME_NAME}}:/downloads \
          fab/image-scraper:latest
