version: '3'
includes:
  fab-scraper:
    dir: ./apps/fab-scraper/
    taskfile: ./apps/fab-scraper/Taskfile.yml
  image-converter:
    dir: ./apps/fab-image-converter/
    taskfile: ./apps/fab-image-converter/Taskfile.yml
  image-text-extractor:
    dir: ./apps/fab-image-details-extractor/
    taskfile: ./apps/fab-image-details-extractor/Taskfile.yml
tasks:
  build:
    cmds:
      - task: fab-scraper:build
      - task: image-converter:build
      - task: image-text-extractor:build
  bootstrap:
    cmds:
      - docker volume create fab-cards-scraped
      - docker volume create fab-cards-prepared
      - docker volume create fab-cards-models
      - task image-text-extractor:bootstrap
  scrape:
    cmd: task fab-scraper:scrape-all
  convert:
    cmd: task image-converter:convert-all
  extract:
    cmd: task image-text-extractor:extract
  run:
    cmds:
      - task build
      - task bootstrap
      - task scrape
      - task convert
      - task extract
  # get-data-from-scraper:
  #   cmds:
  #     - mkdir -p fab-cards
  #     - docker run --rm -v fab-cards:/from -v $(pwd)/fab-cards:/to alpine sh -c "cp -a /from/. /to/"
  #     - sudo chown -R $USER:$USER $(pwd)/fab-cards
  #     - sudo chmod -R u+rw $(pwd)/fab-cards
