version: '3'
dotenv: ['.env']
includes:
  image-scraper:
    dir: ./apps/fab-image-scraper/
    taskfile: ./apps/fab-image-scraper/Taskfile.yml
tasks:
  build:
    cmds:
      - task: image-scraper:build
  scrape:
    cmds:
      - task: image-scraper:run
