version: '3'
includes:
  image-scraper:
    dir: ./apps/fab-image-scraper/
    taskfile: ./apps/fab-image-scraper/Taskfile.yml
  image-converter:
    dir: ./apps/fab-image-converter/
    taskfile: ./apps/fab-image-converter/Taskfile.yml
tasks:
  build:
    cmds:
      - task: image-scraper:build
      - task: image-converter:build
  scrape:
    cmd: task image-scraper:scrape-all
  convert:
    cmd: task image-converter:convert-all
  get-data-from-scraper:
    cmds:
      - mkdir -p fab-cards
      - docker run --rm -v fab-cards:/from -v $(pwd)/fab-cards:/to alpine sh -c "cp -a /from/. /to/"
      - sudo chown -R $USER:$USER $(pwd)/fab-cards
      - sudo chmod -R u+rw $(pwd)/fab-cards
