version: '3'
dotenv: ['.env']
includes:
  image-scraper:
    dir: ./apps/image-scraper/
    taskfile: ./apps/image-scraper/Taskfile.yml
tasks:
  build:
    cmds:
      - task: image-scraper:buld
  scrape:
    cmds:
      - task: image-scraper:scrape
