version: '3'
includes:
  fab-scraper:
    dir: ./apps/fab-scraper/
    taskfile: ./apps/fab-scraper/Taskfile.yml
  fab-text-extractor:
    dir: ./apps/fab-text-extractor/
    taskfile: ./apps/fab-text-extractor/Taskfile.yml
tasks:
  build:
    cmds:
      - task: fab-scraper:build
      - task: fab-text-extractor:build
  bootstrap:
    cmds:
      - docker volume create fab-cards-scraped
      - docker volume create fab-cards-prepared
      - docker volume create fab-cards-models
      - docker volume create fab-cards-text-extracts-db
      - task fab-text-extractor:bootstrap
  scrape:
    cmd: task fab-scraper:scrape-all
  prepare:
    cmd: task fab-scraper:prepare-all
  extract:
    cmd: task fab-text-extractor:extract-all
  run:
    cmds:
      - task build
      - task bootstrap
      - task scrape
      - task prepare
      - task extract
  # get-data-from-scraper:
  #   cmds:
  #     - mkdir -p fab-cards
  #     - docker run --rm -v fab-cards:/from -v $(pwd)/fab-cards:/to alpine sh -c "cp -a /from/. /to/"
  #     - sudo chown -R $USER:$USER $(pwd)/fab-cards
  #     - sudo chmod -R u+rw $(pwd)/fab-cards
