version: '3'
tasks:
  build:
    cmd: docker build . -t fab/image-details-extractor:latest
  bootstrap:
    vars:
      MODELS_DIR: /models
      LANGUAGE_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/v1.3/english_g2.zip
      TEXT_DETECTION_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/craft_mlt_25k.zip
    cmds:
      - docker volume create fab-models
      - |
        docker run --rm \
        -v fab-models:{{$.MODELS_DIR}} \
        -e LANGUAGE_MODEL_URL={{$.LANGUAGE_MODEL_URL}} \
        -e TEXT_DETECTION_MODEL_URL={{$.TEXT_DETECTION_MODEL_URL}} \
        -e MODELS_DIR={{$.MODELS_DIR}} \
        fab/image-details-extractor:latest fab_bootstrap
  extract:
    vars:
      FAB_CARDS_VOLUME: fab-cards
      MODELS_DIR: /models
      IMG_SRC_DIR: /img_src
    cmds:
      - |
        docker run --rm \
        -v fab-models:{{$.MODELS_DIR}} \
        -v {{$.FAB_CARDS_VOLUME}}:{{$.IMG_SRC_DIR}} \
        -e IMG_SRC_DIR={{$.IMG_SRC_DIR}} \
        fab/image-details-extractor:latest fab_extract
