version: '3'
vars:
  DOCKER_IMAGE_NAME: fab/scraper:1.2.0
tasks:
  build:
    cmd: docker build . -t {{.DOCKER_IMAGE_NAME}}
  scrape:
    desc: Scrape card images from a given page URL
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      DOWNLOAD_CONCURRENCY: '{{.DOWNLOAD_CONCURRENCY | default "3"}}'
      DOCKER_VOLUME_NAME: '{{.DOCKER_VOLUME_NAME | default "fab-cards-scraped"}}'
      PAGE_URL: '{{.PAGE_URL}}'
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -e PAGE_URL={{.PAGE_URL}} \
      -e LOG_LEVEL=${LOG_LEVEL} \
      -e DOWNLOAD_DIR=/downloads/{{.SET_NAME}} \
      -e DOWNLOAD_CONCURRENCY={{.DOWNLOAD_CONCURRENCY}} \
      -v {{.DOCKER_VOLUME_NAME}}:/downloads \
      {{.DOCKER_IMAGE_NAME}} fab_scraper
  prepare:
    desc: Prepare scraped images
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      SRC_DOCKER_VOLUME_NAME: '{{.SRC_DOCKER_VOLUME_NAME | default "fab-cards-scraped"}}'
      TARGET_DOCKER_VOLUME_NAME: '{{.TARGET_DOCKER_VOLUME_NAME | default "fab-cards-prepared"}}'
      SRC_VOUME_MOUNT_DIR: /src-dir
      TARGET_VOLUME_MOUNT_DIR: /tartget-dir
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -v {{.SRC_DOCKER_VOLUME_NAME}}:{{.SRC_VOUME_MOUNT_DIR}} \
      -v {{.TARGET_DOCKER_VOLUME_NAME}}:{{.TARGET_VOLUME_MOUNT_DIR}} \
      -e LOG_LEVEL=${LOG_LEVEL} \
      -e SRC_DIR={{.SRC_VOUME_MOUNT_DIR}}/{{.SET_NAME}} \
      -e TARGET_DIR={{.TARGET_VOLUME_MOUNT_DIR}}/{{.SET_NAME}} \
      {{.DOCKER_IMAGE_NAME}} fab_preparator
  scrape-all:
    cmds:
      - task: scrape
        vars:
          SET_NAME: welcome-to-rathe
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/welcome-rathe-booster/
      - task: scrape
        vars:
          SET_NAME: welcome-to-rathe-unlimited
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/welcome-rathe-unlimited-booster/
      - task: scrape
        vars:
          SET_NAME: arcane-rising
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/arcane-rising/
      - task: scrape
        vars:
          SET_NAME: arcane-rising-unlimited
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/arcane-rising-unlimited-booster/
      - task: scrape
        vars:
          SET_NAME: crucible-of-war
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/crucible-war-booster/
      - task: scrape
        vars:
          SET_NAME: monarch
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/monarch-booster/
      - task: scrape
        vars:
          SET_NAME: monarch-unlimited
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/monarch-booster-unlimited/
  prepare-all:
    cmds:
      - task: prepare
        vars:
          SET_NAME: welcome-to-rathe
