services:
  fab-search-db:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fab-app
      POSTGRES_PASSWORD: ${FAB_SEARCH_DB_PASSWORD}
    volumes:
      - fab-search-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  fab-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fab/backend:1.0.0
    ports:
      - 8080:8080
    environment:
      SEARCH_DB_DSN: postgres://postgres:${FAB_SEARCH_DB_PASSWORD}@fab-search-db:5432/fab-app?sslmode=disable
      APP_LISTENER_PORT: 8080
    depends_on:
      fab-search-db:
        condition: service_healthy
volumes:
  fab-search-db:
    name: fab-search-db
    external: true
