version: '3'
tasks:
  build:
    cmd: docker build . -t fab/image-segmentation:latest
  segment:
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      SRC_DOCKER_VOLUME: '{{.SRC_DOCKER_VOLUME | default "fab-cards-converted"}}'
      TARGET_DOCKER_VOLUME: '{{.TARGET_DOCKER_VOLUME | default "fab-cards-segmented"}}'
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -v {{.SRC_DOCKER_VOLUME}}:/source \
      -v {{.TARGET_DOCKER_VOLUME}}:/target \
      -e LOG_LEVEL=${LOG_LEVEL} \
      -e SRC_DIR=/source/{{.SET_NAME}} \
      -e TARGET_DIR=/target/{{.SET_NAME}} \
      fab/image-segmentation:latest
  segment-all:
    cmds:
      - task: segment
        vars:
          SET_NAME: welcome-to-rathe
