network_params:
  input_channel: 1
  output_channel: 512
  hidden_size: 256
# imgH: 64
# imgW: 600
batch_size: 32
workers: 4
num_epochs: 50
lr: 0.001
saved_model: /models
train_data: /dataset/train
valid_data: /dataset/val
train_labels: /app/labels.txt
# charset_file: /app/charset.txt
