version: '3'
tasks:
  build:
    cmd: docker build . -t fab/image-trainer:latest
  train:
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      SRC_DOCKER_VOLUME: '{{.SRC_DOCKER_VOLUME | default "fab-cards-segmented"}}'
      TARGET_DOCKER_VOLUME: '{{.TARGET_DOCKER_VOLUME | default "fab-cards-models"}}'
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -v {{.SRC_DOCKER_VOLUME}}:/dataset \
      -v {{.TARGET_DOCKER_VOLUME}}:/models \
      -e LOG_LEVEL=${LOG_LEVEL} \
      -e SRC_DIR=/dataset \
      -e TARGET_DIR=/models \
      fab/image-trainer:latest
  train-all:
    cmds:
      - task: train
