version: '3'
tasks:
  build:
    cmd: docker build . -t fab/image-scraper:latest
  scrape:
    desc: Scrape card images from a given page URL
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      DOWNLOAD_CONCURRENCY: '{{.DOWNLOAD_CONCURRENCY | default "3"}}'
      DOCKER_VOLUME_NAME: '{{.DOCKER_VOLUME_NAME | default "fab-cards"}}'
      PAGE_URL: '{{.PAGE_URL}}'
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -e PAGE_URL={{.PAGE_URL}} \
      -e LOG_LEVEL=${LOG_LEVEL} \
      -e DOWNLOAD_DIR={{.DOWNLOAD_DIR}}/{{.SET_NAME}} \
      -e DOWNLOAD_CONCURRENCY={{.DOWNLOAD_CONCURRENCY}} \
      -v {{.DOCKER_VOLUME_NAME}}:/downloads \
      fab/image-scraper:latest
  scrape-all:
    cmds:
      - task: scrape
        vars:
          SET_NAME: welcome-to-rathe
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/welcome-rathe-booster/
      - task: scrape
        vars:
          SET_NAME: welcome-to-rathe-unlimited
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/welcome-rathe-unlimited-booster/
      - task: scrape
        vars:
          SET_NAME: arcane-rising
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/arcane-rising/
      - task: scrape
        vars:
          SET_NAME: arcane-rising-unlimited
          PAGE_URL: https://fabtcg.com/en/resources/card-galleries/arcane-rising-unlimited-booster/
