version: '3'
tasks:
  build:
    cmd: docker build . -t fab/text-extractor:latest
  bootstrap:
    vars:
      MODELS_DIR: /models
      LANGUAGE_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/v1.3/english_g2.zip
      TEXT_DETECTION_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/craft_mlt_25k.zip
    cmds:
      - docker volume create fab-cards-models
      - |
        docker run --rm \
        -v fab-cards-models:{{$.MODELS_DIR}} \
        -e LANGUAGE_MODEL_URL={{$.LANGUAGE_MODEL_URL}} \
        -e TEXT_DETECTION_MODEL_URL={{$.TEXT_DETECTION_MODEL_URL}} \
        -e MODELS_DIR={{$.MODELS_DIR}} \
        fab/text-extractor:latest fab_bootstrap
  extract:
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      FAB_CARDS_VOLUME: fab-cards-prepared
      MODELS_DIR: /models
      IMG_SRC_DIR: /img_src
      SET_NAME: '{{.SET_NAME}}'
    cmds:
      - |
        docker run --rm \
        -v fab-cards-models:{{$.MODELS_DIR}} \
        -v {{$.FAB_CARDS_VOLUME}}:{{$.IMG_SRC_DIR}} \
        -e LOG_LEVEL=${LOG_LEVEL} \
        -e IMG_SRC_DIR={{$.IMG_SRC_DIR}}/{{.SET_NAME}} \
        -e MODELS_DIR={{$.MODELS_DIR}}/model \
        fab/text-extractor:latest fab_extract
  extract-all:
    cmds:
      - task: extract
        vars:
          SET_NAME: welcome-to-rathe
