version: '3'
vars:
  DOCKER_IMAGE_NAME: fab/text-extractor:1.3.0
tasks:
  build:
    cmd: docker build . -t {{.DOCKER_IMAGE_NAME}}
  bootstrap:
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      DB_MOUNT_POINT: /text-extracts-db
      DB_NAME: text-extracts.sqlite
      MODELS_DIR: /models
      MODEL_NAME: v1.3-default
      LANGUAGE_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/v1.3/english_g2.zip
      TEXT_DETECTION_MODEL_URL: https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/craft_mlt_25k.zip
    cmds:
      - docker volume create fab-cards-models
      - |
        docker run --rm \
        -v fab-cards-models:{{$.MODELS_DIR}} \
        -v fab-cards-text-extracts-db:{{$.DB_MOUNT_POINT}} \
        -e LOG_LEVEL=${LOG_LEVEL} \
        -e LANGUAGE_MODEL_URL={{$.LANGUAGE_MODEL_URL}} \
        -e TEXT_DETECTION_MODEL_URL={{$.TEXT_DETECTION_MODEL_URL}} \
        -e MODELS_DIR={{$.MODELS_DIR}} \
        -e MODEL_NAME={{$.MODEL_NAME}} \
        -e DB_PATH={{$.DB_MOUNT_POINT}}/{{$.DB_NAME}} \
        {{.DOCKER_IMAGE_NAME}} fab_bootstrap
  extract:
    env:
      LOG_LEVEL: '{{.LOG_LEVEL | default "info"}}'
    vars:
      DB_MOUNT_POINT: /text-extracts-db
      DB_NAME: text-extracts.sqlite
      FAB_CARDS_VOLUME: fab-cards-prepared
      MODELS_DIR: /models
      MODEL_NAME: v1.3-default
      IMG_SRC_DIR: /img_src
      SET_NAME: '{{.SET_NAME}}'
    cmds:
      - |
        docker run --rm \
        -v fab-cards-models:{{$.MODELS_DIR}} \
        -v fab-cards-text-extracts-db:{{$.DB_MOUNT_POINT}} \
        -v {{$.FAB_CARDS_VOLUME}}:{{$.IMG_SRC_DIR}} \
        -e LOG_LEVEL=${LOG_LEVEL} \
        -e IMG_SRC_DIR={{$.IMG_SRC_DIR}}/{{.SET_NAME}} \
        -e MODELS_DIR={{$.MODELS_DIR}}/{{$.MODEL_NAME}} \
        -e DB_PATH={{$.DB_MOUNT_POINT}}/{{$.DB_NAME}} \
        {{.DOCKER_IMAGE_NAME}} fab_extract
  extract-all:
    cmds:
      - task: extract
        vars:
          SET_NAME: welcome-to-rathe
      - task: extract
        vars:
          SET_NAME: welcome-to-rathe-unlimited
      - task: extract
        vars:
          SET_NAME: arcane-rising
      - task: extract
        vars:
          SET_NAME: arcane-rising-unlimited
      - task: extract
        vars:
          SET_NAME: crucible-of-war
      - task: extract
        vars:
          SET_NAME: crucible-of-war-unlimited
      - task: extract
        vars:
          SET_NAME: monarch
      - task: extract
        vars:
          SET_NAME: monarch-unlimited
