version: '3'
tasks:
  build:
    cmds:
      - docker build . -t fab/image-converter:latest
  convert:
    vars:
      SET_NAME: '{{.SET_NAME}}'
    cmd: |
      docker run --rm \
      -v fab-cards-scraped:/source_images \
      -v fab-cards-converted:/target_images \
      -e SOURCE_DIR=/source_images/{{.SET_NAME}} \
      -e TARGET_DIR=/target_images/{{.SET_NAME}} \
      fab/image-converter:latest
  convert-all:
    cmds:
      - task: convert
        vars:
          SET_NAME: welcome-to-rathe
      - task: convert
        vars:
          SET_NAME: welcome-to-rathe-unlimited
      - task: convert
        vars:
          SET_NAME: arcane-rising
      - task: convert
        vars:
          SET_NAME: arcane-rising-unlimited
